### ISSUE TITLE
Add CloudWatch Access to Lambda Policies

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/dos-azul-lambda#22]
In order for the DOS Lambda to be easy to debug and have proper logging, the lambda must be able to create logs in CloudWatch.  This can be solved by add the following json item in the The Dos Azul lambda's AWS access policy.

```json
{
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
}
```

**Comment by david4096** [comment]
I think this closed with https://github.com/DataBiosphere/dos-azul-lambda/pull/28/files#diff-04c6e90faac2675aa89e2176d2eec7d8R121

@GPelayo confirm/deny?

**Comment by GPelayo** [comment]
Yes, the pull request you linked resolves this issue. I'll close it.
