### ISSUE TITLE
Add custom schema to repo

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/dos-azul-lambda#29]
This DOS does not present the entirety of DOS endpoints. To better assist clients in using the service, it should expose a swagger.json that is specific to the endpoints it hosts. This currently requires manually curation from the upstream schemas but could be generated from code in this repository using something like https://github.com/gangverk/flask-swagger .

Can close by curating the endpoints in DOS to what is presented by this lambda from the OpenAPI schema, and then making it available via the `/swagger.json` endpoint. Suggestions for how to reduce manual curation time in the future are appreciated.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-19)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-19
┆Epic: DAL One point ohh

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Should be put off as we may implement bundles.
