### ISSUE TITLE
/test_token should return 401 on bad token

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/dos-azul-lambda#34]
https://github.com/DataBiosphere/dos-azul-lambda/blob/13278afd170f1df5188ca06ce1eba157c8554244/app.py#L91

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-24)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-24
┆Epic: DAL One point ohh

**Comment by david4096** [comment]
Yep!
