### ISSUE TITLE
Isolate testing environment

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/dos-azul-lambda#36]
Ideally, the testing environment should be isolated - one way to do this would be to configure the test suite to spin up a Docker container with ES prepped to resemble the current setup. (Related to #32)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-26)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-26
┆Epic: DAL One point ohh

**Comment by david4096** [comment]
This would be a good way to formalize the relationship to the azul-index. We should be able to create a "test dump" of the azul index to ingest into a local ES for testing.

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

We’ll just suggest folks supply their own domain for testing and use one we configure in aws for our CI testing (for now).
