### ISSUE TITLE
Fix checksum querying in list_data_objects

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/dos-azul-lambda#49]
Querying with `?alias=md5:12345` should work but `?checksum=md5:12345` does not

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-37)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-37

**Comment by david4096** [comment]
+1 currently unimplemented

**Comment by natanlao** [comment]
Duplicate of #3
