### ISSUE TITLE
Python 3 support (DOS-Azul-Lambda)

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/dos-azul-lambda#58]
Add Python 3 support and make sure that the supported versions are noted (PyPI badge?). Also test using Python 3 in Travis

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-44)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-44
┆Epic: DAL One point ohh

**Comment by mikebaumann** [comment]
Thanks for opening this, @natanlao!
Effectively all of our other current development for Commons is in Python 3, and our DOS Lambda(s) should be, too!
