### ISSUE TITLE
Requesting swagger.json causes 500

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/dos-azul-lambda#60]
Because of PyYAML packaging problems.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-45)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-45

**Comment by david4096** [comment]
https://dos.commons.ucsc-cgp.org/swagger.json

**Comment by david4096** [comment]
Also the link to the swagger doc is broken https://github.com/DataBiosphere/dos-azul-lambda/blob/master/app.py#L304 should be `openapi` not swagger.

**Comment by david4096** [comment]
This issue is related to release from another architecture than lambda. For now, just remove the swagger endpoint.

**Comment by david4096** [comment]
The link to the correct swagger is wrong:

https://github.com/DataBiosphere/dos-azul-lambda/pull/62/commits/9979d03b14a664bd5bbd8ac6ef7931e928f8e5a4#diff-3f41e546893dc64b71aaacad12cad815R304

**Comment by natanlao** [comment]
Closed by #68
