### ISSUE TITLE
Data Bundles endpoints 500 if no index is present

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/dos-azul-lambda#67]
~~```
GET /databundles
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 670, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 273, in list_data_bundles
    results = es_query(query={}, index=INDEXES['data_bdl'], size=per_page + 1)
  File "/var/task/app.py", line 142, in es_query
    raise RuntimeError("ElasticSearch returned an unexpected response")
RuntimeError: ElasticSearch returned an unexpected response
```


To close this, modify the GetDataBundles endpoint so that it returns a proper HTTP response code if no data bundle index is present in the provided `ES_HOST`.



┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-49)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-49

**Comment by cricketsloan** [comment]
[~sradesh] and [~nalao] where did you get with this?  You should check to see if putting the name DAL‌-49 in the PR will sync it with the ticket
